#19: Static field in ClientsList, #20: ClientsList name, #21 Not final field in ClientWebView
KirillSmirnow/vpn-router pull request #22
Opened 2024-08-30 16:44 UTC by shurshurik

Update the clients table

2024-08-30 16:47 UTC, shurshurik commented on vpn-router-web/src/main/java/vpnrouter/web/ClientStorage.java
> +public class ClientStorage {
To be honest I'm not sure that it's the best solution but it works and it's better that it was before =)

2024-09-03 11:03 UTC, KirillSmirnow commented on vpn-router-web/src/main/java/vpnrouter/web/ClientStorage.java
> +public class ClientStorage {
hahaha

2024-09-03 11:04 UTC, KirillSmirnow requested changes
Requires discussion...

2024-09-03 15:02 UTC, shurshurik commented on vpn-router-web/src/main/java/vpnrouter/web/ClientStorage.java
> +public class ClientStorage {
Do you have any other ideas?))

2024-09-03 15:45 UTC, KirillSmirnow commented on vpn-router-web/src/main/java/vpnrouter/web/ClientStorage.java
> +public class ClientStorage {
Why do you think that this solution is "better that it was before"?

2024-09-03 15:48 UTC, shurshurik commented on vpn-router-web/src/main/java/vpnrouter/web/ClientStorage.java
> +public class ClientStorage {
Because this class encapsulates a selected row of the grid and we can autowire it as a final field

2024-09-03 15:51 UTC, KirillSmirnow commented on vpn-router-web/src/main/java/vpnrouter/web/ClientStorage.java
> +public class ClientStorage {
Seems awful. Requires discussion...

2024-09-03 15:53 UTC, shurshurik commented on vpn-router-web/src/main/java/vpnrouter/web/ClientStorage.java
> +public class ClientStorage {
okay) I'll try to find another solution)

2024-09-04 17:38 UTC, KirillSmirnow approved these changes

2024-09-04 17:59 UTC, merged