#32: Client detection
KirillSmirnow/vpn-router pull request #52
Opened 2024-09-09 15:03 UTC by shurshurik

Add a button to detect new clients

2024-09-09 15:25 UTC, KirillSmirnow requested changes

2024-09-09 15:25 UTC, KirillSmirnow commented on vpn-router-bootstrap/build.gradle.kts
> +    implementation("com.vaadin:vaadin-spring-boot-starter:24.4.8")
No, bootstrap may not depend on web

2024-09-09 15:25 UTC, KirillSmirnow commented on vpn-router-bootstrap/src/main/java/vpnrouter/VpnRouter.java
> +public class VpnRouter extends SpringBootServletInitializer implements AppShellConfigurator {
No, bootstrap may not depend on web

2024-09-09 15:25 UTC, KirillSmirnow commented on vpn-router-api/src/main/java/vpnrouter/api/client/ClientDetectionService.java
> +        void onStart();
No, you've broken the logic: this is a completion listener and onStart is not completion.

We may redesign the behavior.

2024-09-09 15:25 UTC, KirillSmirnow commented on vpn-router-web/src/main/java/vpnrouter/web/ui/clients/ClientDetectionButtonFactory.java
> +                }
Brackets should open and close together on same correspondent lines like this:
```
[<((  // opening 1
({({  // opening 2

// some code

})})  // closing 2
))>]  // closing 1
```

2024-09-09 15:25 UTC, KirillSmirnow commented on vpn-router-web/src/main/java/vpnrouter/web/ui/clients/ClientDetectionButtonFactory.java
> +                    UI ui = event.getSource().getUI().orElseThrow();
```suggestion
                    var ui = UI.getCurrent();
```

2024-09-09 15:25 UTC, KirillSmirnow commented on vpn-router-web/src/main/java/vpnrouter/web/ui/clients/ClientsPage.java
> +        return clientDetectionButtonFactory.build();
The wrapping method is redundant

2024-09-09 15:25 UTC, KirillSmirnow commented on vpn-router-web/src/main/java/vpnrouter/web/ui/clients/CompetitionListenerImpl.java
> +    private final int DELAY_MILLISECONDS = 1000;
Let's go somewhere and learn how to declare constants in Java

2024-09-09 15:25 UTC, KirillSmirnow commented on vpn-router-web/src/main/java/vpnrouter/web/ui/clients/CompetitionListenerImpl.java
> +    private final int DELAY_MILLISECONDS = 1000;
Why kind of delay is this (should be specified)?

2024-09-09 15:25 UTC, KirillSmirnow commented on vpn-router-web/src/main/java/vpnrouter/web/ui/clients/CompetitionListenerImpl.java
> +    private final int DELAY_MILLISECONDS = 1000;
```suggestion
    private final int DELAY_IN_MILLISECONDS = 1000;
```

2024-09-09 15:25 UTC, KirillSmirnow commented on vpn-router-web/src/main/java/vpnrouter/web/ui/clients/CompetitionListenerImpl.java
> +    private final int DELAY_MILLISECONDS = 1000;
better: `Duration myDelay = Duration.ofSeconds(1)`

2024-09-09 15:25 UTC, KirillSmirnow commented on vpn-router-web/src/main/java/vpnrouter/web/ui/clients/CompetitionListenerImpl.java
> +public class CompetitionListenerImpl implements ClientDetectionService.CompletionListener {
🐶 🐕 🦮

2024-09-09 15:25 UTC, KirillSmirnow commented on vpn-router-web/src/main/java/vpnrouter/web/ui/clients/CompetitionListenerImpl.java
> +        ui.access(() -> {
It seems code format is poor here

2024-09-09 15:25 UTC, KirillSmirnow commented on vpn-router-web/src/main/java/vpnrouter/web/ui/clients/CompetitionListenerImpl.java
> +                                    ui.access(() -> ui.getPage().reload());
Page reloading is too rough method to refresh data -- should be a bit smarter/optimal

2024-09-09 15:38 UTC, KirillSmirnow commented on vpn-router-web/src/main/java/vpnrouter/web/ui/clients/ClientsPage.java
> +        var button = new Button(VaadinIcon.PLUS.create());
👍

2024-09-10 15:19 UTC, shurshurik commented on vpn-router-web/src/main/java/vpnrouter/web/ui/clients/CompetitionListenerImpl.java
> +public class CompetitionListenerImpl implements ClientDetectionService.CompletionListener {
What do you mean?))

2024-09-19 07:50 UTC, closed without merging